# Generated by Django 5.2.7 on 2025-10-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport', models.FloatField()),
                ('energy', models.FloatField()),
                ('food', models.FloatField()),
                ('waste', models.FloatField()),
                ('total_emission', models.FloatField()),
                ('suggestion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
