# Generated by Django 5.2.7 on 2025-10-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_met', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonFootprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_distance', models.FloatField(default=0)),
                ('flight_hours', models.FloatField(default=0)),
                ('public_trips', models.FloatField(default=0)),
                ('electricity', models.FloatField(default=0)),
                ('gas', models.FloatField(default=0)),
                ('meat_meals', models.FloatField(default=0)),
                ('local_food', models.FloatField(default=0)),
                ('waste_kg', models.FloatField(default=0)),
                ('recycling', models.FloatField(default=0)),
                ('water_liters', models.FloatField(default=0)),
                ('showers', models.FloatField(default=0)),
                ('online_orders', models.FloatField(default=0)),
                ('clothing', models.FloatField(default=0)),
                ('total_footprint', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='CarbonRecord',
        ),
    ]
