# Generated by Django 5.2.7 on 2025-10-26 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_met', '0003_carbonfootprint_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLPipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('emissions', models.FloatField(help_text='Carbon emissions in kg CO₂eq')),
                ('duration', models.FloatField(help_text='Training time in seconds')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
