# Generated by Django 5.2.7 on 2025-10-27 03:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_met', '0005_remove_mlpipelinerun_name_mlpipelinerun_dataset_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('training_time', models.FloatField(help_text='Training time in hours')),
                ('hardware', models.CharField(choices=[('cpu', 'CPU'), ('gpu', 'GPU'), ('tpu', 'TPU')], max_length=10)),
                ('energy_consumed', models.FloatField(help_text='Energy consumption in kWh')),
                ('emission', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='MLPipelineRun',
        ),
    ]
